class ConstMeta(type):
    def __setattr__(self, name, value):
        if name in self.__dict__:
            raise TypeError(f'Can\'t rebind const ({name})')
        else:
            self.__setattr__(name, value)

class NMASConstants(metaclass =ConstMeta):
    """NMAS利用定数宣言"""
    # BP追加時に追加が必要な定数群
    STR_ABUILD_C_MAIL_GET_QUERY = 'from:Abuild就活 NINJAPAN <info@abuild-c.com> subject:(就活 予約 無料相談)'
    STR_ABUILD_TECH_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:【Tech】予約_無料相談'
    STR_ABUILD_CAREER_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:【キャリア】予約_無料相談'
    STR_ABUILD_LINECASE_MAIL_GET_QUERY = 'from:【就活力診断】フィードバック＆個別相談センター <info@abuild-c.com> subject:_無料相談フィードバック申込'
    STR_ABUILD_SHIRUBE_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:【しるべ】予約_無料相談'
    STR_ABUILD_REFERRAL_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:【紹介予約】無料相談申込が1件あります'
    # STR_ABUILD_REASHU_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 就活の教科書 予約 無料相談)'
    # STR_ABUILD_Z_UNI_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 Z 大学 予約 無料相談)'
    # STR_ABUILD_WAKARU_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 wakaru就活 予約 無料相談)'
    # STR_ABUILD_MP_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 MP 予約 無料相談)'
    # STR_ABUILD_OTOSHIDAMA_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(Abuild 無料個別説明会 お年玉 キャンペーン)'
    # STR_ABUILD_SERVICE_HP_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 service_HP 予約 無料相談)'
    # STR_ABUILD_HIGHCLASS_HP_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 highclass_HP 予約 無料相談)'
    # STR_ABUILD_PROFESSIONAL_HP_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 professional_HP 予約 無料相談)'
    # STR_ABUILD_SERVICE_1224_HP_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 service_1224 予約 無料相談)'
    # STR_ABUILD_HP_BOOKING_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 hp_booking 予約 無料相談)'
    # STR_ABUILD_SERVICE_1224_GY_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 service_1224_gy 予約 無料相談)'
    # STR_ABUILD_SERVICE_1224_FB_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 service_1224_fb 予約 無料相談)'
    # STR_ABUILD_SERVICE_1224_GL_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 service_1224_gl 予約 無料相談)'
    # STR_ABUILD_PROFESSIONAL_AU23_FB_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 professional_au23_fb 予約 無料相談)'
    # STR_ABUILD_N_CH_BOOKING_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 n-ch_booking 予約 無料相談)'
    # STR_ABUILD_BIZUAL_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 bizual 予約 無料相談)'
    # STR_ABUILD_PORT_MAIL_GET_QUERY = 'from:<info@abuild-c.com> subject:(就活 ポート 予約 無料相談)'
    # STR_ABUILD_ORIENTATION_NOTIFICATION_MAIL_GET_QUERY = 'from:	<info@abuild-c.com> subject:(オリエンテーション 日程確定)'

    FOLDER_PATH_LOGS = '../Logs/'
    FOLDER_PATH_ABUILDC = 'Abuildc/'
    
    STR_MAILDATA_KEY_MARKET_ROOT_DATA = '【流入経路】'
    STR_MAILDATA_KEY_FULLNAME = '【氏名】'
    STR_MAILDATA_KEY_AGE = '【年齢】'
    STR_MAILDATA_KEY_FIRST_COUNSELING_DATE = '【初回面談日】'
    STR_MAILDATA_KEY_COUSELING_COURSE = '【受講形式】'
    STR_MAILDATA_KEY_UNIVERSITY_DATA = '【大学】'
    STR_MAILDATA_KEY_MAILADDRESS = '【メールアドレス】'
    STR_MAILDATA_KEY_MAILADDRESS_CHECK = '【メールアドレス（確認用）】'
    STR_MAILDATA_KEY_PHONENUMBER = '【携帯電話】'
    STR_MAILDATA_KEY_RESPONSIBLE_TIMEZONE = '【電話可能な時間】'

    STR_ABUILDC_CATEGORY = '就活'
    STR_DEFAULT_STEP ='002初回確定'
    STR_LINECASE_INFLUX_PATH ='L_就活相談'
    STR_ABUILDTECH_CATEGORY = 'Tech'
    STR_ABUILDCAREER_CATEGORY = 'キャリア'
    STR_ABUILDLINECASE_CATEGORY = 'LINE診断'
    STR_ABUILDLINECASE_SHORT_CATEGORY = 'LINE'
    STR_ABUILDSHIRUBE_CATEGORY = 'しるべ'
    STR_ABUILDREFERRAL_CATEGORY = '紹介予約'
    
    # BP追加時に追加変更は想定していない定数群
    STR_ABUILD_SALES_INFO_SEETS = "'見込み顧客管理_V2'!A:A"
    STR_LF = '\n'
    STR_MAIL_INFO_START_LINE = '＝＝＝＝予約内容＝＝＝＝'
    STR_MAIL_INFO_END_LINE = '＝＝＝＝＝＝＝＝＝＝＝＝'
    STR_MAIL_INFO_COACHING_AREA_BORDER = '---'
    STR_ME = 'me'
    STR_MESSAGES = 'messages'
    STR_SUCCESS = 'SUCCESS'
    STR_GET = 'GET'
    STR_ERROR0101 = 'ERROR-0101'
    STR_ERROR0102 = 'ERROR-0102'
    STR_ERROR8000 = 'ERROR-8000'
    STR_ERROR9900 = 'ERROR-9900'
    STR_TYPE_ONLINE = '【受講形式】オンライン'
    STR_DELIMITER = ' , '
    STR_BLANK = ''
    STR_FALSE = 'FALSE'
    STR_TRUE = 'TRUE'
    STR_EQUAL = '='
    STR_COMMA = ','
    STR_SPACE = ' '
    STR_SOTSU = '卒'
    STR_SLASH = '/'
    STR_MESSAGE_BLANK = '未記入'
    STR_NOTIFICATION_END_TITLE = '＝＝＝＝＝＝＝＝＝＝＝＝'
    STR_ORIENTATION_MAIL_FORMAT_START_BORDER = '＝＝＝TR-OR＝＝＝'
    
    MESSAGE_CHECK_DATA = 'CHECK DATA:'
    MESSAGE_WRITING_UPDATE_DATA = 'WRITING UPDATE DATA:'
    MESSAGE_WRITING_DATA = 'WRITING DATA:'
    MESSAGE_WRITING_INSERT_DATA = 'WRITING INSERT DATA:'
    MESSAGE_FILE_CREATE = 'FILE CREATE:'
    MESSAGE_MAIL_NOT_FOUND = 'MAIL NOT FOUND'
    MESSAGE_INS_PROC_END = '===========================\n'
    
    KEY_PAYLOAD = 'payload'
    KEY_PARTS = 'parts'
    KEY_BODY = 'body'
    KEY_DATA = 'data'
    KEY_SIZE = 'size'

    FILE_NAME_DATA_INSERT_ID_CSV = 'data_insert_id.csv'
    CSV_INSERT_ID_CSV_HEADER_GMAILID = 'GMailId'
    CSV_INSERT_ID_CSV_HEADER_STATUS = 'Status'
    CSV_INSERT_ID_CSV_HEADER_BODYDATA = 'BodyData'
    CSV_INSERT_ID_CSV_HEADER_INSERTTIME = 'InsertTime'
    CSV_HEADER_ERRORMAIL_FULL_CSV = '[DataName], [Level1], [Level2], [Level3], [Level4], [Level5], [Level6], [Level7]'

    FORMAT_INS_PROC_START = '={0}データ入力処理========'
    FORMAT_NOTIFICATION_START_TITLE = '＝＝{0}予約内容＝＝＝＝'
    FORMAT_NOTIFICATION_TITLE = '＝＝{0}＝＝＝＝'
    FORMAT_REFERRAL_NOTIFICATION_START_TITLE = '＝＝＝＝ {0} ＝＝＝＝'
    FORMAT_NOTIFICATION_REFERRALER = '紹介者： {0}'
    FORMAT_BRAKETS = '[{0}]'
    FORMAT_QUOTATION_BRAKETS = '"{0}"'
    FORMAT_ASTERISK_BRAKETS = '*{0}*'
    FORMAT_FILE_NAME_CONV_TXT = '{0}_conv.txt'
    FORMAT_FILE_NAME_ERRORMAIL_FULL_CSV = '{0}_errormail_full.csv'
    FORMAT_LOG_LINE = '{0},{1},{2},{3}'
    FORMAT_INSERT_PROCESS_CANCEL_LINE_TEXT = '{0}[{1}]:書き込み済みのため処理を飛ばします。'
    FORMAT_INSERT_PROCESS_ERROR_UNMATCH_LINE_TEXT = '[{0}]メールが検索出来ません。メールIDが不正です。'
    FORMAT_INSERT_PROCESS_ERROR0101_LINE_TEXT = '{0}[{1}]:処理出来ないメールデータのため処理を飛ばします。詳細はLogsフォルダを確認してください。'
    FORMAT_INSERT_PROCESS_ERROR0102_LINE_TEXT = '{0}[{1}]:メール内容が完全に重複するメールデータのため処理を飛ばします。詳細はLogsフォルダを確認してください。'
    FORMAT_INSERT_PROCESS_ERROR8000_LINE_TEXT = '{0}[{1}]:Slack通知が出来なかったため通知処理を飛ばします。詳細はLogsフォルダを確認してください。'
    FORMAT_INSERT_PROCESS_ERROR9900_LINE_TEXT = '{0}[{1}]:メールのデータフォーマットが不正のため処理を飛ばします。詳細はLogsフォルダを確認してください。'
    FORMAT_INSERT_PROCESS_START_LINE_TEXT = '{0}:未処理のメールデータです。'
    FORMAT_ERROR_RESULT_ERROR_LINE_TEXT = '[{0}]:API経由の検索結果にエラーが発生しています。'
    FORMAT_ERROR_INCONSISTENCY_LINE_TEXT = '[{0}]:検索と書き込みの間に削除された可能性があるため、処理できません。'
    FORMAT_FIRSTDATE_NF = '=IFERROR(VLOOKUP(INDIRECT("S"&ROW()),\'初回日時用データシート\'!$A:$B,2,false),{0})'  
    
    REFERRAL_SERVICE_DICTIONARY = {'Abuild 就活':'就活', 'Abuild Tech':'Tech'}

    # STR_NAME_NF = '=INDIRECT("AM"&ROW())'
    # STR_AGE_NF = '=INDIRECT("AN"&ROW())'
    # STR_APP_MONTH_NF = '=MONTH(INDIRECT("AO"&ROW()))'
    # STR_APP_DAY_NF = '=DAY(INDIRECT("AO"&ROW()))'
    STR_MONTH_NF = '=MONTH(INDIRECT("O"&ROW()))'
    STR_DAY_NF = '=MAX(INDIRECT("O"&ROW()):INDIRECT("Q"&ROW()))'
    # STR_AFFIL_NF = '=INDIRECT("AQ"&ROW())'   
    # STR_MADRS_NF = '=INDIRECT("AR"&ROW())'     
    # STR_PHONE_NF = '=INDIRECT("AS"&ROW())'      
    # STR_CALLTIME_NF = '=INDIRECT("AT"&ROW())'

# import sys
# sys.modules[__name__] = NMASConstants()